name: Rename file on push

on:
  push:
    branches:
      - main

jobs:
  rename-file:
    runs-on: ubuntu-latest

    # защита от рекурсии
    if: "!contains(github.event.head_commit.message, '[auto-rename]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Rename file
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          mv artifact.txt artifact-${TIMESTAMP}.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "[auto-rename] rename artifact file"

      - name: Push changes
        run: |
          git push
